### PR TITLE
Bigblade -O3

### PR DESCRIPTION
**Pull request by mrutt92**

### CODE REVIEW

**Review by drichmond — APPROVED** [review]
Sure, but why?

**Comment by drichmond** [comment]
LGTM

**Comment by mrutt92** [comment]
1. It should have always been this way. IMO, the fact that it's been -O0 is a bug.
2. When running host software on RISCV simulation platforms like Dromajo and BlackParrot, every instruction matters.

**Comment by drichmond** [comment]
Yep, saw the slack thread. -Os might be worth trying, too.

**Comment by mrutt92** [comment]
To be clear, I meant every instruction executed. Sripathi tried -Os and saw that the code size was not much improved over -O3.

**Pull request merged**
