### PR TITLE
Acceleration of simulation IO with back door to DRAM data store

### PR DESCRIPTION
**Pull request by mrutt92**
Relies on https://github.com/bespoke-silicon-group/basejump_stl/pull/236
Relies on https://github.com/bespoke-silicon-group/bsg_manycore/pull/232

This is still a WIP. To really work we need a way to notify caches that they should invalidate all their data. Writing works pretty well for most of our CUDA applications by first of the fact that we typically don't access the memory locations we write to before calling memcpy().

Reading the results out is totally broken ATM because of the cache issue which is why `#define DRAM_HACK_READ` is commented out.

### CODE REVIEW

**Comment by mrutt92** [comment]
BTW - I haven't measured the speedup yet but I have a rough idea, from observing, that it's crazy good.

**Comment by drichmond** [comment]
Great! As part of the experiments, can you run a kernel which is small, a 1x1 tile group, and has very little DRAM data?

Borna and I can provide one if this works seamlessly with baseline

**Comment by mrutt92** [comment]
How much is "very little?"

and does it actually need to run anything?

**Comment by mrutt92** [comment]
and also why? the whole point is to speedup IO with large input.

**Comment by drichmond** [comment]
512 words, ish. The vector-vector add example that I referred to in #505 is adding two 128 element vectors.

**Comment by drichmond** [comment]
Yes, this is exactly my point in #505

**Comment by mrutt92** [comment]
I mean... it's not going to provide much of a speedup for an application with no DRAM data - the problem of initializing a bunch of tiles is not the problem that this PR attempts to solve.

This PR addresses a problem we have when we need to move a large amount (like megabytes) of input data into the device's DRAM and it takes hour just to perform IO but likely not much time to actually do the compute.

The issue you raise in #505 is an important one but it's not addressed by this PR (nor is it meant to be).

**Comment by mrutt92** [comment]
Admittedly this PR is addressing an issue that those of us who are working on graph applications are running into, but maybe not so much for the ML and linear algebra folks.

**Comment by drichmond** [comment]
I have no beef with this PR, I think it's a great PR. I look forward to switching to the C++ models and this will really make our cosimulation sing.

**Comment by drichmond** [comment]
Both issues are addressing an important issue that Cornell raised today - why does it take so long to do initialization when your ROI is only 5000 cycles

**Comment by drichmond** [comment]
So timely, and great.

**Comment by taylor-bsg** [comment]
A couple of different alternatives to address the incoherency issue:

a. add a backdoor function to the vcache implementations that magically
updates any bytes in the cache. If the line is not dirty, it could just
invalidate the line. Messy, because there are transient states.

b. Add a host routine that issues a stream of tagla’s to read the tags out
of the caches. Then issue a stream of parallel tagfl, tagsw instructions to
invalidate any potential conflicts. This could be useful for our silicon
where we are hosting the DRAM on an FPGA or PC via ASIC memory backdoor
interface. We could do direct writes to the DRAM without having to go over
the I/O link to the ASIC.



M

**Comment by mrutt92** [comment]
> b. Add a host routine that issues a stream of tagla’s to read the tags out
of the caches. Then issue a stream of parallel tagfl, tagsw instructions to
invalidate any potential conflicts. This could be useful for our silicon
where we are hosting the DRAM on an FPGA or PC via ASIC memory backdoor
interface. We could do direct writes to the DRAM without having to go over
the I/O link to the ASIC.

@taylor-bsg yeah - I was thinking of a solution more in the vein of (b).

**Comment by drichmond** [comment]
Weird idea - but could we have the manycore array somehow clear the tags? Then it could be done in parallel when the cores boot?

**Comment by mrutt92** [comment]
I was thinking that instead of TAGFL, TAGST, TAGL we might want to use AFL before DRAM reads and AINV after DRAM writes?

**Comment by mrutt92** [comment]
Oh wait, I see that TAGL and TAGST are already be supported? Just set the high-order EPA bit to 1?

**Comment by mrutt92** [comment]
The problem that I see with going down this road (by which I mean relying on TGSTW, TAGLA, and flushing in *either* hardware or software) is it would mean doing a fair amount of IO in simulation just to deal with the cache. N-way associativity means you have to either do up to N-loads to find the tag you want to invalidate and then do a store *OR*  just do. N-stores to invalidate the whole set. Flushing would be painful for similar reasons. 

None of this seems like a big deal for actual hardware (where, frankly, the problem addressed by this PR is completely moot) but this cost in simulation would eat away at the gains from this PR and it would not scale with associativity. In fact, if associativity is greater than a line size in words, this actually makes IO worse because you would ultimately be sending more packets onto the network than if you just performed IO directly by the host-interface. You could keep track of sets that have already been invalidated/flushed and not repeat yourself, and then your worst case is the size of the cache, but that's still a bummer.

That's why I'm wondering if we shouldn't just add support for AINV and AFL somehow. It's lame to add hardware for the reason of simulating faster though...

**Comment by vb000** [comment]
> a. add a backdoor function to the vcache implementations that magically updates any bytes in the cache. If the line is not dirty, it could just invalidate the line. Messy, because there are transient states.

Since the backdoor is solely for simulation, isn't this a better choice? If we have a non-synthesizable sv function in vcache, which could be invoked to initializes cache-lines with the same data being loaded to the dram while maintaining the state (dirty bit), transient states are undisturbed, right?

**Comment by taylor-bsg** [comment]
Max, afl is for small chunks of data and tagfl is for large ranges of
address space. Both are useful generally for doing software coherence, but
in our use case afl would be proportionally the same cost to write the data
into the cache directly over the network than use afl. The beauty of tagfl
is I can flush a gigabyte of data just by scanning 1024 tags.

M

**Comment by mrutt92** [comment]
Well... I ended up going with more or less @taylor-bsg's suggestion.

**Comment by drichmond** [comment]
Replaced by #521

**Pull request closed without merging**
