### PR TITLE
Adding _DEFAULT_SOURCE macro

### PR DESCRIPTION
**Pull request by dpetrisko**
Newer versions of glibc require this macro to be set alongside _BSD_SOURCE and _GNU_SOURCE: https://stackoverflow.com/questions/29201515/what-does-d-default-source-do

### CODE REVIEW

**Review by drichmond — APPROVED** [review]

**Comment by mrutt92** [comment]
uh... err... were we suppose to merge this?

**Comment by dpetrisko** [comment]
Let me update it then #shipit

**Comment by dpetrisko** [comment]
Good to go

**Comment by mrutt92** [comment]
awesome possum. and you promise that this will 100% not breaking everything, right? ;-)

**Comment by dpetrisko** [comment]
It's only 84 files, how much damage could I do? :D

**Comment by mrutt92** [comment]
Good enough for me!

**Pull request merged**
