### PR TITLE
Removing nb_waw_detector from the bsg_replicant

### PR DESCRIPTION
**Pull request by bornaehsani**
Related to PR # 316 in bsg_manycore.

### CODE REVIEW

**Comment by drichmond** [comment]
Does it pass regression on timing_v0_8_4, 4x4_fast_n_fake, and 4x4_blocking_vcache_f1_model?

**Comment by bornaehsani** [comment]
Yes forgot to mention again! Cosim passes on 4x4_fast_n_fake, 4x4_blocking_vcache_f1_model, and timing_v0_8_4.

**Comment by taylor-bsg** [comment]
Don't we want this so that we can simulate the silicon?

**Comment by drichmond** [comment]
Howso? This branch is post-hardfloat, and my understanding is that the WAW detector isn't necessary anymore. It was removed from spmd_testbench in @tommydcjung's hardfloat PR https://github.com/bespoke-silicon-group/bsg_manycore/commit/3bea19e18ff9452dd92917a7d930ff76dd28d404#diff-16eb0cad8f6be38876d7b0f7f9455ec5L1006

**Pull request merged**
