### PR TITLE
Python cmd args

### PR DESCRIPTION
**Pull request by vb000**
- Added support for arbitrary python command line arguments in test_loader.

### CODE REVIEW

**Comment by vb000** [comment]
Yes Dustin, test_python in the regression suite can be done this way... if we are okay with breaking the `+c_args="<test_dir> <test_name>"` invariant.

**Comment by drichmond** [comment]
OK. If it only applies to test_python I'm not concerned. 

Looks good to me, do you want me to merge it?

**Comment by vb000** [comment]
Sure.

**Comment by vb000** [comment]
> OK. If it only applies to test_python I'm not concerned.
> 
> Looks good to me, do you want me to merge it?

Let's make this change in test_python then?

**Comment by drichmond** [comment]
You can if you want. I added test_python mostly to show how to integrate python. Nobody has added additional functionality, so I'm not concerned with the way it is right now.

**Comment by vb000** [comment]
Okay, just to have the flexibility in case we need it, I changed it in #562.

**Pull request merged**
