### PR TITLE
Update Verilator link.mk

### PR DESCRIPTION
**Pull request by dpetrisko**
- Here I remove -j and rely on the user to do make -j
- We could also do -j$(NUM_THREADS) or something
- -j by itself starts infinite jobs and crashes my laptop

### CODE REVIEW

**Comment by mrutt92** [comment]
strong reject

**Comment by mrutt92** [comment]
jk

**Review by mrutt92 — APPROVED** [review]

**Comment by drichmond** [comment]
I used to have an NPROC (or similar) variable for VCS compilation. It would determine the number of threads in the system and then divide by four. 

Should be in the git history somewhere. 

But if you don't want to track it down, LGTM

**Review by taylor-bsg — APPROVED** [review]

**Comment by dpetrisko** [comment]
good to go?

**Pull request merged**
